services:
  redis:
    image: docker.io/redis:8.6.2-alpine
    ports:
      - 6379:6379

  rabbitmq:
    image: docker.io/rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    restart: unless-stopped
