use types::{NonEmpty, TrimmedString, nonempty_trimmed_string};

/// A validated, non-empty text message used in chat interactions.
///
/// Wraps a `NonEmpty<TrimmedString>` to guarantee that messages sent to
/// or received from the AI are neither completely empty nor just whitespace.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Message(pub NonEmpty<TrimmedString>);

impl Message {
    /// Attempts to create a new [`Message`] from a [`String`].
    ///
    /// Returns [`None`] if the provided string is empty or contains only whitespace.
    pub fn new(s: String) -> Option<Self> {
        NonEmpty::new(TrimmedString::from(s)).map(Self)
    }
}

impl std::ops::Deref for Message {
    type Target = NonEmpty<TrimmedString>;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

#[allow(clippy::from_over_into)]
impl Into<genai::chat::MessageContent> for Message {
    fn into(self) -> genai::chat::MessageContent {
        let trimmed_string = self.0.into_inner();
        genai::chat::MessageContent::from_text(trimmed_string.into_inner())
    }
}

/// Defines the author or context of a chat message.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ChatRole {
    /// High-level instructions that guide the AI's behavior.
    System,
    /// Input provided by the human user.
    User,
    /// Responses generated by the AI model.
    Assistant,
}

#[allow(clippy::from_over_into)]
impl Into<genai::chat::ChatRole> for ChatRole {
    fn into(self) -> genai::chat::ChatRole {
        match self {
            Self::System => genai::chat::ChatRole::System,
            Self::User => genai::chat::ChatRole::User,
            Self::Assistant => genai::chat::ChatRole::Assistant,
        }
    }
}

/// A single turn in a chat conversation, pairing a specific role with text content.
#[derive(Debug, Clone)]
pub struct ChatMessage {
    /// The author of the message.
    pub role: ChatRole,
    /// The actual text content.
    pub content: Message,
}

impl ChatMessage {
    /// Creates a new [`ChatMessage`] with the specified `role` and `content`.
    pub fn new(role: ChatRole, content: Message) -> Self {
        Self { role, content }
    }

    /// Convenience method to create a [`ChatRole::System`] message.
    pub fn system(content: Message) -> Self {
        Self::new(ChatRole::System, content)
    }

    /// Convenience method to create a [`ChatRole::User`] message.
    pub fn user(content: Message) -> Self {
        Self::new(ChatRole::User, content)
    }

    /// Convenience method to create a [`ChatRole::Assistant`] message.
    pub fn assistant(content: Message) -> Self {
        Self::new(ChatRole::Assistant, content)
    }
}

#[allow(clippy::from_over_into)]
impl Into<genai::chat::ChatMessage> for ChatMessage {
    fn into(self) -> genai::chat::ChatMessage {
        genai::chat::ChatMessage {
            role: self.role.into(),
            content: self.content.into(),
            options: None,
        }
    }
}

/// The complete payload for a chat interaction, containing the conversation history.
///
/// This structure isolates the `system` message (if any) and holds the sequential
/// list of `messages` exchanged between the user and the assistant.
#[derive(Debug, Clone, Default)]
pub struct ChatRequest {
    pub system: Option<Message>,
    pub messages: Vec<ChatMessage>,
}

impl ChatRequest {
    /// Creates a new [`ChatRequest`] from an optional `system` prompt and an initial list of `messages`.
    pub fn new(system: Option<Message>, messages: Vec<ChatMessage>) -> Self {
        Self { system, messages }
    }

    /// Builder method to attach or replace the `system` message.
    pub fn with_system(mut self, system: Message) -> Self {
        self.system = Some(system);
        self
    }

    /// Builder method to append a new `message` to the conversation history.
    pub fn push_message(&mut self, message: ChatMessage) -> &mut Self {
        self.messages.push(message);
        self
    }
}

#[allow(clippy::from_over_into)]
impl Into<genai::chat::ChatRequest> for ChatRequest {
    fn into(self) -> genai::chat::ChatRequest {
        genai::chat::ChatRequest {
            system: self.system.map(|msg| msg.to_string()),
            messages: self.messages.into_iter().map(Into::into).collect(),
            tools: None,
        }
    }
}

/// Represents the token consumption metrics for an AI request.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[allow(clippy::struct_field_names)]
pub struct Usage {
    /// The number of tokens consumed by the input prompt.
    pub prompt_tokens: u32,
    /// The number of tokens consumed by the generated response.
    pub completion_tokens: u32,
    /// The total combined tokens used for the interaction.
    pub total_tokens: u32,
}

#[allow(clippy::cast_sign_loss)]
impl From<&genai::chat::Usage> for Usage {
    fn from(value: &genai::chat::Usage) -> Self {
        let prompt_tokens = value.prompt_tokens.map(|t| t as u32).unwrap_or_default();
        let completion_tokens = value
            .completion_tokens
            .map(|t| t as u32)
            .unwrap_or_default();

        Self {
            prompt_tokens,
            completion_tokens,
            total_tokens: prompt_tokens + completion_tokens,
        }
    }
}

/// The result returned from a successful chat execution.
///
/// Contains both the generated text `content` and the token `usage` metrics.
#[derive(Debug, Clone)]
pub struct ChatResponse {
    /// The text generated by the AI assistant.
    pub content: Message,
    /// The token usage metrics for this specific interaction.
    pub usage: Usage,
}

impl From<genai::chat::ChatResponse> for ChatResponse {
    fn from(value: genai::chat::ChatResponse) -> Self {
        Self {
            usage: Usage::from(&value.usage),
            content: Message::new(value.into_texts().join("")).unwrap_or_else(|| {
                Message(nonempty_trimmed_string!(
                    "Response did not contain valid text"
                ))
            }),
        }
    }
}

/// A wrapper error type for failures originating from the underlying [`genai::Client`] operations.
#[derive(Debug, thiserror::Error)]
#[error(transparent)]
pub struct ExecChatError(#[from] genai::Error);
